import {
  ArrowRight,
  ArrowUpDown,
  Bold,
  BookOpen,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronLeft,
  CloudOff,
  Code,
  Copy,
  Eye,
  EyeOff,
  Flashlight,
  FlashlightOff,
  Heading,
  Highlighter,
  Hourglass,
  Image,
  ImageOff,
  Inbox,
  Info,
  Italic,
  Languages,
  Layers,
  List,
  ListOrdered,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  Minus,
  MoreHorizontal,
  Pencil,
  Plus,
  RotateCcw,
  ScanLine,
  Search,
  Send,
  Settings,
  Share2,
  Sparkles,
  Table,
  Ticket,
  Trash2,
  Type,
  User,
  UserPlus,
  Users,
  WifiOff,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const iconRegistry: Record<string, LucideIcon> = {
  'arrow-right': ArrowRight,
  'arrow-up-down': ArrowUpDown,
  'bold': Bold,
  'book-open': BookOpen,
  'check': Check,
  'check-check': CheckCheck,
  'check-circle-2': CheckCircle2,
  'chevron-left': ChevronLeft,
  'cloud-off': CloudOff,
  'code': Code,
  'copy': Copy,
  'eye': Eye,
  'eye-off': EyeOff,
  'flashlight': Flashlight,
  'flashlight-off': FlashlightOff,
  'heading': Heading,
  'highlighter': Highlighter,
  'hourglass': Hourglass,
  'image': Image,
  'image-off': ImageOff,
  'inbox': Inbox,
  'info': Info,
  'italic': Italic,
  'languages': Languages,
  'layers': Layers,
  'list': List,
  'list-ordered': ListOrdered,
  'loader-circle': LoaderCircle,
  'lock': Lock,
  'log-out': LogOut,
  'mail': Mail,
  'minus': Minus,
  'more-horizontal': MoreHorizontal,
  'pencil': Pencil,
  'plus': Plus,
  'rotate-ccw': RotateCcw,
  'scan-line': ScanLine,
  'search': Search,
  'send': Send,
  'settings': Settings,
  'share-2': Share2,
  'sparkles': Sparkles,
  'table': Table,
  'ticket': Ticket,
  'trash-2': Trash2,
  'type': Type,
  'user': User,
  'user-plus': UserPlus,
  'users': Users,
  'wifi-off': WifiOff,
  'x': X,
  'zap': Zap,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
};

export type IconName = keyof typeof iconRegistry;
