import {
  ArrowRight,
  ArrowUpDown,
  BookOpen,
  Check,
  CheckCheck,
  ChevronLeft,
  CloudOff,
  Code,
  Copy,
  Highlighter,
  Hourglass,
  Image,
  ImageOff,
  Inbox,
  Info,
  Languages,
  Layers,
  Lock,
  Mail,
  MoreHorizontal,
  Plus,
  RotateCcw,
  ScanLine,
  Search,
  Send,
  Settings,
  Sparkles,
  Ticket,
  User,
  UserPlus,
  Users,
  WifiOff,
  X,
  Zap,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const iconRegistry: Record<string, LucideIcon> = {
  'arrow-right': ArrowRight,
  'arrow-up-down': ArrowUpDown,
  'book-open': BookOpen,
  'check': Check,
  'check-check': CheckCheck,
  'chevron-left': ChevronLeft,
  'cloud-off': CloudOff,
  'code': Code,
  'copy': Copy,
  'highlighter': Highlighter,
  'hourglass': Hourglass,
  'image': Image,
  'image-off': ImageOff,
  'inbox': Inbox,
  'info': Info,
  'languages': Languages,
  'layers': Layers,
  'lock': Lock,
  'mail': Mail,
  'more-horizontal': MoreHorizontal,
  'plus': Plus,
  'rotate-ccw': RotateCcw,
  'scan-line': ScanLine,
  'search': Search,
  'send': Send,
  'settings': Settings,
  'sparkles': Sparkles,
  'ticket': Ticket,
  'user': User,
  'user-plus': UserPlus,
  'users': Users,
  'wifi-off': WifiOff,
  'x': X,
  'zap': Zap,
};

export type IconName = keyof typeof iconRegistry;
